# Generated by Django 4.0 on 2021-12-14 02:23

from django.db import migrations, models
import posts_apis.helpers.src.image_file


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=posts_apis.helpers.src.image_file.ImageManage.set_image_file)),
                ('published', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, max_length=120)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-create_at',),
            },
        ),
    ]
