# Generated by Django 4.0 on 2021-12-08 18:09

from django.db import migrations, models
import posts_apis.helpers.src.image_file


class Migration(migrations.Migration):

    dependencies = [
        ('posts_apis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='image',
            field=models.ImageField(blank=True, upload_to=posts_apis.helpers.src.image_file.ImageManage.set_image_file),
        ),
    ]
