# Generated by Django 4.0 on 2021-12-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_apis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostObject',
        ),
    ]
