# Generated by Django 4.0 on 2021-12-12 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_apis', '0002_delete_postobject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
