# Generated by Django 4.0 on 2021-12-10 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts_apis', '0002_alter_posts_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ('-create_at',)},
        ),
    ]
