# Generated by Django 4.0 on 2021-12-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('avatar', models.ImageField(blank=True, upload_to='user/')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='username')),
                ('nickname', models.CharField(max_length=50, verbose_name='Nickname')),
                ('first_name', models.CharField(blank=True, max_length=25, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=25, verbose_name='Last name')),
                ('email', models.CharField(max_length=50, unique=True, verbose_name='Email address')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Phone number')),
                ('github', models.CharField(blank=True, max_length=150, verbose_name='Github account')),
                ('bio', models.CharField(blank=True, max_length=250, verbose_name='Bio')),
                ('date_join', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
